# Documentation
# https://docs.docker.com/compose/compose-file

version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  eventstore:
    image: eventstore/eventstore
    ports:
      - 2113:2113
      - 1113:1113
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    networks:
      - backend

  # boilerplate-nodejs-cqrs-es-swagger:
  #   build:
  #     context: "."
  #   command: ${CONTAINER_COMMAND}
  #   restart: always
  #   deploy:
  #     mode: replicated
  #     replicas: ${CONTAINER_SCALE}
  #   depends_on:
  #     - eventstore
  #   env_file:
  #     - "./.env"
  #   environment:
  #     - EVENT_STORE_HOSTNAME=eventstore
  #   ports:
  #     - "${CONTAINER_PORT}:7070"
  #   volumes:
  #     - "./src:/app/src"
  #   links:
  #     - eventstore
  #   networks:
  #     - backend

networks:
  backend:
    driver: bridge
